### ISSUE TITLE
evaluation

### ISSUE THREAD

**Issue by karim-gasmi** [turner11/VQA-MED#48]
Hi,
If i have two file (ground truth file and submission file with .txt version like asked by imageclef,
can you help me by clarified how can i use your code to calculate WBSS and other metric with .txt imputs
Thank in advance

**Comment by turner11** [comment]
Sure   
It has been 2 years since I have last dealt with the code, so I'll have to refresh my memory :)  
can you send a sample of the files for me to test on?

**Comment by karim-gasmi** [comment]
Hi,
I have already sent the files by email, have you received
Thank you in advance

**Comment by turner11** [comment]
Yes I have.
I'll get around to it on Friday...

**Comment by turner11** [comment]
Using the 2 files you sent me ([VQAMed2020-Task1-VQAnswering-Test-ReferenceAnswers.txt](https://github.com/turner11/VQA-MED/files/7351875/VQAMed2020-Task1-VQAnswering-Test-ReferenceAnswers.txt) and [run-submition.txt](https://github.com/turner11/VQA-MED/files/7351876/run-submition.txt))  

See this quick example (Note that the score is 1 since they have the same content):


```python
import pandas as pd
from pathlib import Path
from evaluate.VqaMedEvaluatorBase import VqaMedEvaluatorBase
```


```python
reference_answers_path = Path("VQAMed2020-Task1-VQAnswering-Test-ReferenceAnswers.txt")
predictions_path = Path('run-submition.txt')

assert reference_answers_path.exists(), "reference file does not exsists"
assert predictions_path.exists(), "predictions file does not exsists"
```


```python
df_answers = pd.read_csv(str(reference_answers_path), sep="|", header=None, names=["image", 'answer'])
df_predictions = pd.read_csv(str(predictions_path), sep="|", header=None, names=["image", 'prediction'])
```

```python
df = df_predictions.join(df_answers[['answer']])
df.head()
```

<div>

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>image</th>
      <th>prediction</th>
      <th>answer</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>synpic26840</td>
      <td>no</td>
      <td>no</td>
    </tr>
    <tr>
      <th>1</th>
      <td>synpic39181</td>
      <td>yes</td>
      <td>yes</td>
    </tr>
    <tr>
      <th>2</th>
      <td>synpic36496</td>
      <td>yes</td>
      <td>yes</td>
    </tr>
    <tr>
      <th>3</th>
      <td>synpic25800</td>
      <td>no</td>
      <td>no</td>
    </tr>
    <tr>
      <th>4</th>
      <td>synpic25633</td>
      <td>no</td>
      <td>no</td>
    </tr>
  </tbody>
</table>
</div>




```python
predictions = df.prediction.values
ground_truth = df.answer.values
results = VqaMedEvaluatorBase.get_all_evaluation(predictions=predictions, ground_truth=ground_truth)
```


```python
results
```




    {'strict_accuracy': 1.0, 'bleu': 1.0, 'wbss': 1.0}

**Comment by turner11** [comment]
@karim-gasmi , If this answers your question, please close the issue.

**Comment by karim-gasmi** [comment]
@turner11  Thank you for your help :)
